### PR TITLE
Rfc 2136

### PR DESCRIPTION
**Pull request by ross**
/cc https://github.com/octodns/octodns/pull/930 which this requires and will need to be shipped before this module is released
/cc Fixes https://github.com/octodns/octodns/issues/927#issuecomment-1238834192 @siilike
/cc Replaces https://github.com/octodns/octodns-ddns/pull/10/files

/cc @yzguy main question here is whether this should be stand alone now or if i should just make these changes in octoDNS core. i'm on the fence, given that it's all RFC stuff.

### CODE REVIEW

**Comment by yzguy** [comment]
I think in it's own makes sense, RFC2136 is just specifically about dynamic updates so it's really more of the method/API we are using versus us implementing the RFC itself.

After this is good to go, deprecating ZoneFileSource + AxfrSource from octodns core makes sense.

**Comment by ross** [comment]
> I think in it's own makes sense, RFC2136 is just specifically about dynamic updates so it's really more of the method/API we are using versus us implementing the RFC itself.

Makes sense.

> After this is good to go, deprecating ZoneFileSource + AxfrSource from octodns core makes sense.

That't be the rough plan. Cut a release with the functionality required by this PR. Cut a release of this module. Then do the same sort of warning stuff in core for the existing `axfr.*` that the other providers have.

**Comment by ross** [comment]
Now that octoDNS 0.9.20 has been released with the rdata/text support built into Record this module is ready to :ship:

**Comment by ross** [comment]
Going to go ahead and merge this since it's a completely new module. We'll call it beta for now, not that it means anything :grin:

**Pull request merged**
